# -*- coding: utf-8 -*-
"""AI Investment Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUM1DeKyRfcrPBkqN6xktoyR4YTAY7qa
"""

# ==============================
# INSTALL & IMPORT LIBRARIES
# ==============================

import sys
import subprocess

packages = [
    "yfinance",
    "google-generativeai",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "ipywidgets",
    "jinja2"
]

for package in packages:
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", package],
        check=False
    )

# Imports
import os
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import google.generativeai as genai
import getpass
import json
import warnings

from datetime import datetime, timedelta
from IPython.display import display, HTML, Markdown, clear_output
import ipywidgets as widgets

warnings.filterwarnings("ignore")

# Styling
sns.set_theme(style="darkgrid")

plt.rcParams["figure.figsize"] = (12,6)
plt.rcParams["figure.facecolor"] = "white"

print("✅ Setup Completed Successfully")

import os
import getpass
import google.generativeai as genai

# Configure Google Gemini API Client
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    print("🔑 GEMINI_API_KEY environment variable not found in system.")
    api_key = getpass.getpass("Please input your Google Gemini API Key: ")
    os.environ["GEMINI_API_KEY"] = api_key

try:
    genai.configure(api_key=api_key)
    # Verify connectivity
    model = genai.GenerativeModel('gemini-2.5-flash')
    verification_resp = model.generate_content("Test connection. Respond with: API connected!")
    print(f"🌍 Gemini API Status: {verification_resp.text.strip()}")
except Exception as e:
    print(f"❌ Configuration failed: {e}")
    print("Please verify your API key is correct and you have internet access.")

def resolve_tickers_and_intent(query):
    """
    Uses Gemini AI to parse the user's query, determine the intent,
    and resolve company names into Yahoo Finance ticker symbols (NSE/US).
    """
    model = genai.GenerativeModel('gemini-2.5-flash')

    prompt = f"""
    Analyze the following user query for financial analysis intent:
    \"{query}\"

    Extract the following information and return strictly as a JSON object:
    1. "intent": String. Must be one of:
       - "single_analysis" (user wants details on one stock, e.g., "Should I invest in Tata Motors?")
       - "compare" (user wants to compare two stocks, e.g., "Compare Reliance and Infosys")
       - "sector_recommendation" (user asks about sectors or best stocks overall, e.g., "Which sector is strong?", "Best stocks to invest in India")
       - "general_qa" (general market or investing question)
    2. "companies": List of strings. Company names mentioned in the query.
    3. "tickers": List of strings. Resolved Yahoo Finance tickers for each company.
       Rules for tickers:
       - For prominent Indian companies (e.g. Tata Motors, Reliance, Infosys, TCS, HDFC Bank, SBI, ICICI, Adani), map to the National Stock Exchange (NSE) ticker ending with '.NS' (e.g. 'TATAMOTORS.NS', 'RELIANCE.NS', 'INFY.NS', 'TCS.NS', 'HDFCBANK.NS', 'SBIN.NS').
       - For US companies (e.g. Apple, Tesla, Nvidia, Microsoft, Amazon, Google, Meta), map to the US exchange ticker (e.g. 'AAPL', 'TSLA', 'NVDA', 'MSFT', 'AMZN', 'GOOGL', 'META').
       - If no company is mentioned, return an empty list.
       - Max 2 tickers.

    Respond with ONLY valid JSON, no markdown blocks, no formatting. Example:
    {{"intent": "single_analysis", "companies": ["Tata Motors"], "tickers": ["TATAMOTORS.NS"]}}
    """

    try:
        response = model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"}
        )
        data = json.loads(response.text.strip())
        return data
    except Exception as e:
        print(f"⚠️ Error in Ticker Resolver: {e}. Defaulting to General Q&A classification.")
        return {"intent": "general_qa", "companies": [], "tickers": []}

def fetch_stock_data(ticker, period="1y"):
    """
    Retrieves historical price data from Yahoo Finance.
    Defaults to 1 year of daily closing prices.
    """
    try:
        stock = yf.Ticker(ticker)
        # Fetch 2 years to ensure we have a full 200-day MA padding even with a 1-year analysis period
        df = stock.history(period="2y" if period=="1y" else period)
        if df.empty:
            print(f"⚠️ Warning: No historical data returned for ticker '{ticker}'.")
            return None
        return df
    except Exception as e:
        print(f"❌ Error querying yfinance for ticker {ticker}: {e}")
        return None

def calculate_indicators(df):
    """
    Applies custom technical analysis indicators on the price DataFrame.
    Calculates SMAs, RSI, MACD, and Bollinger Bands using Pandas/NumPy.
    """
    df = df.copy()
    if len(df) < 200:
        raise ValueError("Dataframe must contain at least 200 trading days to construct moving averages.")

    # 1. Moving Averages (50-day and 200-day Simple Moving Average)
    df['MA50'] = df['Close'].rolling(window=50).mean()
    df['MA200'] = df['Close'].rolling(window=200).mean()

    # 2. Bollinger Bands (20-day SMA + 2 Standard Deviations)
    df['MA20'] = df['Close'].rolling(window=20).mean()
    df['BB_std'] = df['Close'].rolling(window=20).std()
    df['BB_Upper'] = df['MA20'] + (df['BB_std'] * 2)
    df['BB_Lower'] = df['MA20'] - (df['BB_std'] * 2)

    # 3. Relative Strength Index (RSI, 14-day Wilder's smoothed)
    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    # Wilder's exponential moving average smoothing
    avg_gain = gain.ewm(com=13, adjust=False).mean()
    avg_loss = loss.ewm(com=13, adjust=False).mean()

    rs = np.where(avg_loss == 0, 100, avg_gain / avg_loss)
    df['RSI'] = 100 - (100 / (1 + rs))

    # 4. Moving Average Convergence Divergence (MACD)
    df['EMA12'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['EMA26'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = df['EMA12'] - df['EMA26']
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']

    return df

def generate_technical_recommendation(df):
    """
    Evaluates latest indicators and computes a rules-based rating
    and confidence score.
    """
    latest = df.iloc[-1]
    prev = df.iloc[-2]

    signals = {}
    weights = {
        'rsi': 0.25,
        'macd': 0.25,
        'ma_align': 0.30,
        'bb': 0.20
    }

    # 1. RSI Score
    rsi = latest['RSI']
    if rsi < 30:
        signals['rsi'] = (1.0, "Oversold (RSI < 30) - Bullish Indicator")
    elif rsi > 70:
        signals['rsi'] = (-1.0, "Overbought (RSI > 70) - Bearish Indicator")
    elif rsi < 40:
        signals['rsi'] = (0.5, "Moderate Bullish Accumulation Zone")
    elif rsi > 60:
        signals['rsi'] = (-0.5, "Moderate Bearish Distribution Zone")
    else:
        signals['rsi'] = (0.0, "Neutral Momentum")

    # 2. MACD Score
    macd = latest['MACD']
    sig = latest['MACD_Signal']
    hist = latest['MACD_Hist']
    prev_hist = prev['MACD_Hist']

    if hist > 0 and prev_hist <= 0:
        signals['macd'] = (1.0, "Bullish MACD Crossover")
    elif hist < 0 and prev_hist >= 0:
        signals['macd'] = (-1.0, "Bearish MACD Crossover")
    elif macd > sig:
        signals['macd'] = (0.5, "MACD above Signal (Bullish Outlook)")
    else:
        signals['macd'] = (-0.5, "MACD below Signal (Bearish Outlook)")

    # 3. SMA Trend Alignment Score
    price = latest['Close']
    ma50 = latest['MA50']
    ma200 = latest['MA200']

    if price > ma50 > ma200:
        signals['ma_align'] = (1.0, "Golden Trend Alignment (Price > MA50 > MA200)")
    elif price < ma50 < ma200:
        signals['ma_align'] = (-1.0, "Bearish Trend Alignment (Price < MA50 < MA200)")
    elif price > ma50:
        signals['ma_align'] = (0.5, "Short term bullish (Price above MA50)")
    else:
        signals['ma_align'] = (-0.5, "Short term bearish (Price below MA50)")

    # 4. Bollinger Bands Score
    bb_upper = latest['BB_Upper']
    bb_lower = latest['BB_Lower']
    bb_middle = latest['MA20']
    bb_range = bb_upper - bb_lower
    bb_pos = (price - bb_lower) / bb_range if bb_range != 0 else 0.5

    if price <= bb_lower or bb_pos < 0.1:
        signals['bb'] = (1.0, "Price near/below Lower Bollinger Band (Extreme Oversold)")
    elif price >= bb_upper or bb_pos > 0.9:
        signals['bb'] = (-1.0, "Price near/above Upper Bollinger Band (Extreme Overbought)")
    else:
        signals['bb'] = (0.0, f"Neutral BB range (Position: {bb_pos:.1%})")

    # Calculate weighted score
    raw_score = sum(signals[key][0] * weights[key] for key in weights) * 100

    # Recommendation boundaries
    if raw_score >= 25:
        recommendation = "BUY"
    elif raw_score <= -25:
        recommendation = "SELL"
    else:
        recommendation = "HOLD"

    # Scale confidence score
    confidence = int(abs(raw_score))
    confidence = max(20, min(95, confidence)) # bound between 20% and 95%

    return {
        "recommendation": recommendation,
        "confidence_score": confidence,
        "raw_score": raw_score,
        "signals": {k: {"score": signals[k][0], "reason": signals[k][1]} for k in signals},
        "metrics": {
            "current_price": price,
            "ma50": ma50,
            "ma200": ma200,
            "rsi": rsi,
            "macd": macd,
            "macd_signal": sig,
            "bb_upper": bb_upper,
            "bb_lower": bb_lower,
            "bb_middle": bb_middle
        }
    }

def generate_ai_reasoning(ticker, tech_results, company_name=None):
    """
    Queries Gemini AI to generate a detailed analyst research report
    based on computed technical parameters.
    """
    model = genai.GenerativeModel('gemini-2.5-flash')

    metrics = tech_results['metrics']
    signals = tech_results['signals']
    company = company_name if company_name else ticker

    prompt = f"""
    You are a professional financial research analyst and personal investment adviser.
    Analyze this dataset for the company {company} ({ticker}) and generate a short, premium investment report.

    Quantitative Engine Context:
    - Current Closing Price: {metrics['current_price']:.2f}
    - 50-Day Moving Average: {metrics['ma50']:.2f}
    - 200-Day Moving Average: {metrics['ma200']:.2f}
    - RSI (14 Days): {metrics['rsi']:.2f} ({signals['rsi']['reason']})
    - MACD Line: {metrics['macd']:.4f}, Signal Line: {metrics['macd_signal']:.4f} ({signals['macd']['reason']})
    - Bollinger Bands: Upper Band = {metrics['bb_upper']:.2f}, Lower Band = {metrics['bb_lower']:.2f} ({signals['bb']['reason']})

    Recommendation Engine Verdict:
    - Recommendation: {tech_results['recommendation']}
    - Engine Confidence Score: {tech_results['confidence_score']}/100

    Generate the response using markdown headings for these exact sections:
    1. **Executive Summary & Investment Thesis**: Clearly explain why the assistant recommends to Buy, Sell, or Hold. Outline the core technical support or resistances.
    2. **Detailed Technical Interpretation**: Synthesize how indicators converge. (e.g. Is MACD crossing bullishly while RSI is near oversold, etc.?)
    3. **Key Investor Risks & Macro Outlook**: List 2-3 specific risks for this stock (e.g., trend breakdowns, industry specific tailwinds or headwinds, regulatory hurdles) to ensure proper risk management.

    Make your tone professional, concise, and do not use generic text or placeholders.
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"⚠️ Failed to generate AI insights: {e}. Outputting technical statistics only."

def plot_technical_analysis(ticker, df):
    """
    Renders a unified 3-panel professional dashboard plot.
    """
    # View the last 120 trading days (roughly 6 months of data) for clean visuals
    plot_df = df.iloc[-120:]

    fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=True,
                             gridspec_kw={'height_ratios': [2.5, 0.9, 0.9]})

    fig.suptitle(f"{ticker} - Multi-Indicator Technical Analysis Dashboard",
                 fontsize=15, fontweight='bold', color='#1A202C', y=0.98)

    # Axis 0: Price Action, MAs & BBs
    ax0 = axes[0]
    ax0.plot(plot_df.index, plot_df['Close'], label='Closing Price', color='#2B6CB0', linewidth=2)
    ax0.plot(plot_df.index, plot_df['MA50'], label='50-day SMA', color='#D69E2E', linestyle='--', linewidth=1.5)
    ax0.plot(plot_df.index, plot_df['MA200'], label='200-day SMA', color='#E53E3E', linestyle='-.', linewidth=1.5)
    ax0.plot(plot_df.index, plot_df['BB_Upper'], label='BB Upper (2.0 SD)', color='#4A5568', linestyle=':', linewidth=1)
    ax0.plot(plot_df.index, plot_df['BB_Lower'], label='BB Lower (2.0 SD)', color='#4A5568', linestyle=':', linewidth=1)
    ax0.fill_between(plot_df.index, plot_df['BB_Lower'], plot_df['BB_Upper'], color='#CBD5E0', alpha=0.25, label='BB Channel')

    ax0.set_ylabel('Price', fontsize=11, fontweight='semibold')
    ax0.legend(loc='upper left', frameon=True, facecolor='white', edgecolor='#E2E8F0', fontsize=9)
    ax0.set_title("Price Action & Trend Structures", fontsize=11, fontweight='bold', loc='left', pad=6)
    ax0.tick_params(axis='y', labelsize=9)

    # Axis 1: RSI
    ax1 = axes[1]
    ax1.plot(plot_df.index, plot_df['RSI'], label='RSI (14)', color='#805AD5', linewidth=1.5)
    ax1.axhline(70, color='#E53E3E', linestyle='--', linewidth=1.2)  # Overbought line
    ax1.axhline(30, color='#38A169', linestyle='--', linewidth=1.2)  # Oversold line
    ax1.fill_between(plot_df.index, 30, 70, color='#805AD5', alpha=0.06)
    ax1.set_ylabel('RSI', fontsize=11, fontweight='semibold')
    ax1.set_ylim(15, 85)
    ax1.legend(loc='upper left', frameon=True, facecolor='white', edgecolor='#E2E8F0', fontsize=9)
    ax1.set_title("Relative Strength Index (RSI)", fontsize=11, fontweight='bold', loc='left', pad=6)
    ax1.tick_params(axis='y', labelsize=9)

    # Axis 2: MACD
    ax2 = axes[2]
    ax2.plot(plot_df.index, plot_df['MACD'], label='MACD Line', color='#3182CE', linewidth=1.5)
    ax2.plot(plot_df.index, plot_df['MACD_Signal'], label='Signal Line (9)', color='#DD6B20', linewidth=1.5)

    # Color MACD Hist columns
    hist_colors = ['#38A169' if val >= 0 else '#E53E3E' for val in plot_df['MACD_Hist']]
    ax2.bar(plot_df.index, plot_df['MACD_Hist'], label='Histogram', color=hist_colors, alpha=0.6, width=0.8)

    ax2.set_ylabel('MACD', fontsize=11, fontweight='semibold')
    ax2.set_xlabel('Timeline', fontsize=11, fontweight='semibold')
    ax2.legend(loc='upper left', frameon=True, facecolor='white', edgecolor='#E2E8F0', fontsize=9)
    ax2.set_title("MACD (12, 26, 9) Momentum Oscillator", fontsize=11, fontweight='bold', loc='left', pad=6)
    ax2.tick_params(axis='y', labelsize=9)

    plt.tight_layout()
    plt.show()

def analyze_single_stock(ticker, company_name=None):
    """
    Coordinates full single stock workflow: data fetching, calculations, visualization, and AI generation.
    """
    company_label = company_name if company_name else ticker
    print(f"🔍 Retrieving data and running mathematical technical indicators for: {company_label}...")

    df = fetch_stock_data(ticker)
    if df is None or len(df) < 200:
        print(f"❌ Aborting analysis: Insufficient historical data for '{ticker}'. (Need at least 200 trading days).")
        return

    # Indicator Computations
    df = calculate_indicators(df)

    # Recommendation
    tech_res = generate_technical_recommendation(df)

    # Styled Card Output
    rec = tech_res['recommendation']
    conf = tech_res['confidence_score']
    price = tech_res['metrics']['current_price']
    rsi = tech_res['metrics']['rsi']
    ma50 = tech_res['metrics']['ma50']
    ma200 = tech_res['metrics']['ma200']
    macd = tech_res['metrics']['macd']
    bb_upper = tech_res['metrics']['bb_upper']
    bb_lower = tech_res['metrics']['bb_lower']

    colors = {"BUY": "#2F855A", "SELL": "#C53030", "HOLD": "#D69E2E"}
    theme_color = colors.get(rec, "#4A5568")

    card_html = f"""
    <div style=\"padding: 24px; border-radius: 12px; background-color: #F8FAFC; border-left: 8px solid {theme_color}; border-top: 1px solid #E2E8F0; border-bottom: 1px solid #E2E8F0; border-right: 1px solid #E2E8F0; margin: 20px 0; font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;\">
        <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;\">
            <span style=\"font-size: 1.4em; font-weight: bold; color: #2D3748;\">{company_label} ({ticker})</span>
            <span style=\"font-size: 1em; color: #718096;\">As of: {datetime.now().strftime('%Y-%m-%d')}</span>
        </div>
        <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;\">
            <div>
                <p style=\"margin: 0; color: #718096; font-size: 0.9em;\">Current Close</p>
                <p style=\"margin: 4px 0 0 0; font-size: 1.5em; font-weight: bold; color: #1A202C;\">{price:.2f}</p>
            </div>
            <div>
                <p style=\"margin: 0; color: #718096; font-size: 0.9em;\">RSI (14 Days)</p>
                <p style=\"margin: 4px 0 0 0; font-size: 1.5em; font-weight: bold; color: #1A202C;\">{rsi:.1f}</p>
            </div>
            <div>
                <p style=\"margin: 0; color: #718096; font-size: 0.9em;\">Recommendation Rating</p>
                <p style=\"margin: 4px 0 0 0; font-size: 1.6em; font-weight: bold; color: {theme_color};\">{rec}</p>
            </div>
            <div>
                <p style=\"margin: 0; color: #718096; font-size: 0.9em;\">Scoring Confidence</p>
                <p style=\"margin: 4px 0 0 0; font-size: 1.6em; font-weight: bold; color: #2D3748;\">{conf}%</p>
            </div>
        </div>
        <div style=\"margin-top: 15px; padding-top: 15px; border-top: 1px solid #E2E8F0; font-size: 0.95em; color: #4A5568; line-height: 1.5;\">
            <b>Key Indicator Values:</b> MA(50) = <b>{ma50:.2f}</b> | MA(200) = <b>{ma200:.2f}</b> | Bollinger Upper/Lower = <b>{bb_upper:.2f}/{bb_lower:.2f}</b> | MACD Line = <b>{macd:.4f}</b>
        </div>
    </div>
    """
    display(HTML(card_html))

    # Render Plots
    plot_technical_analysis(ticker, df)

    # Generate AI Narrative
    print("✍️ Writing Investment Thesis with Gemini AI...")
    ai_report = generate_ai_reasoning(ticker, tech_res, company_label)
    display(Markdown(ai_report))

def compare_two_stocks(ticker1, ticker2, name1=None, name2=None):
    """
    Performs side-by-side technical evaluation of two stocks.
    """
    n1 = name1 if name1 else ticker1
    n2 = name2 if name2 else ticker2

    print(f"📊 Initializing relative comparison matrix between {n1} ({ticker1}) and {n2} ({ticker2})...")

    df1 = fetch_stock_data(ticker1)
    df2 = fetch_stock_data(ticker2)

    if df1 is None or df2 is None or len(df1) < 200 or len(df2) < 200:
        print("❌ Comparison failed: Insufficient dataset for comparison. Ensure both stock symbols are valid.")
        return

    res1 = generate_technical_recommendation(calculate_indicators(df1))
    res2 = generate_technical_recommendation(calculate_indicators(df2))

    # Calculate short/long returns
    ret1_1m = ((df1['Close'].iloc[-1] - df1['Close'].iloc[-21]) / df1['Close'].iloc[-21]) * 100
    ret2_1m = ((df2['Close'].iloc[-1] - df2['Close'].iloc[-21]) / df2['Close'].iloc[-21]) * 100

    ret1_1y = ((df1['Close'].iloc[-1] - df1['Close'].iloc[0]) / df1['Close'].iloc[0]) * 100
    ret2_1y = ((df2['Close'].iloc[-1] - df2['Close'].iloc[0]) / df2['Close'].iloc[0]) * 100

    t1_bullish = res1['metrics']['current_price'] > res1['metrics']['ma50'] > res1['metrics']['ma200']
    t2_bullish = res2['metrics']['current_price'] > res2['metrics']['ma50'] > res2['metrics']['ma200']

    # Mathematical selection criteria for Short Term Winner
    st1 = 0
    st2 = 0
    if res1['recommendation'] == 'BUY': st1 += 2
    if res2['recommendation'] == 'BUY': st2 += 2
    if res1['metrics']['rsi'] < 40: st1 += 1
    if res2['metrics']['rsi'] < 40: st2 += 1
    if ret1_1m > ret2_1m: st1 += 1.5
    else: st2 += 1.5
    st_winner = n1 if st1 > st2 else n2

    # Long Term Winner Selection
    lt1 = 0
    lt2 = 0
    if t1_bullish: lt1 += 2
    if t2_bullish: lt2 += 2
    if ret1_1y > ret2_1y: lt1 += 2
    else: lt2 += 2
    lt_winner = n1 if lt1 > lt2 else n2

    # Combined Winner
    overall_winner = n1 if (st1 * 0.4 + lt1 * 0.6) > (st2 * 0.4 + lt2 * 0.6) else n2

    # Renders a side-by-side HTML comparison grid
    compare_html = f"""
    <div style=\"overflow-x: auto; margin: 20px 0; font-family: sans-serif;\">
        <table style=\"width: 100%; border-collapse: collapse; text-align: left; background-color: #F8FAFC; border-radius: 8px; overflow: hidden; border: 1px solid #E2E8F0;\">
            <thead>
                <tr style=\"background-color: #2D3748; color: white;\">
                    <th style=\"padding: 12px 16px;\">Performance & Indicator Criteria</th>
                    <th style=\"padding: 12px 16px;\">{n1} ({ticker1})</th>
                    <th style=\"padding: 12px 16px;\">{n2} ({ticker2})</th>
                </tr>
            </thead>
            <tbody>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>Current Close Price</b></td>
                    <td style=\"padding: 10px 16px;\">{res1['metrics']['current_price']:.2f}</td>
                    <td style=\"padding: 10px 16px;\">{res2['metrics']['current_price']:.2f}</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>RSI (14 Days)</b></td>
                    <td style=\"padding: 10px 16px;\">{res1['metrics']['rsi']:.2f}</td>
                    <td style=\"padding: 10px 16px;\">{res2['metrics']['rsi']:.2f}</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>Moving Average Alignment</b></td>
                    <td style=\"padding: 10px 16px; font-weight:bold; color: {'green' if t1_bullish else '#718096'};\">{'Bullish' if t1_bullish else 'Neutral/Bearish'}</td>
                    <td style=\"padding: 10px 16px; font-weight:bold; color: {'green' if t2_bullish else '#718096'};\">{'Bullish' if t2_bullish else 'Neutral/Bearish'}</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>1-Month Return</b></td>
                    <td style=\"padding: 10px 16px; color: {'green' if ret1_1m >= 0 else 'red'};\">{ret1_1m:+.2f}%</td>
                    <td style=\"padding: 10px 16px; color: {'green' if ret2_1m >= 0 else 'red'};\">{ret2_1m:+.2f}%</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>1-Year Return</b></td>
                    <td style=\"padding: 10px 16px; color: {'green' if ret1_1y >= 0 else 'red'};\">{ret1_1y:+.2f}%</td>
                    <td style=\"padding: 10px 16px; color: {'green' if ret2_1y >= 0 else 'red'};\">{ret2_1y:+.2f}%</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0; background-color: #EDF2F7;\">
                    <td style=\"padding: 12px 16px;\"><b>Recommendation Rating</b></td>
                    <td style=\"padding: 12px 16px; font-weight: bold;\">{res1['recommendation']} ({res1['confidence_score']}% Conf)</td>
                    <td style=\"padding: 12px 16px; font-weight: bold;\">{res2['recommendation']} ({res2['confidence_score']}% Conf)</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>Winner (Short-Term Horizon)</b></td>
                    <td colspan=\"2\" style=\"padding: 10px 16px; font-weight: bold; color: #2B6CB0;\">{st_winner}</td>
                </tr>
                <tr style=\"border-bottom: 1px solid #E2E8F0;\">
                    <td style=\"padding: 10px 16px;\"><b>Winner (Long-Term Horizon)</b></td>
                    <td colspan=\"2\" style=\"padding: 10px 16px; font-weight: bold; color: #2B6CB0;\">{lt_winner}</td>
                </tr>
                <tr style=\"background-color: #E2E8F0;\">
                    <td style=\"padding: 12px 16px; font-weight: bold;\">🏆 OVERALL WINNER</td>
                    <td colspan=\"2\" style=\"padding: 12px 16px; font-weight: bold; font-size:1.15em; color: #2F855A;\">{overall_winner}</td>
                </tr>
            </tbody>
        </table>
    </div>
    """
    display(HTML(compare_html))

    print("✍️ Requesting comparative analyst commentary from Gemini AI...")
    model = genai.GenerativeModel('gemini-2.5-flash')
    prompt = f"""
    You are a portfolio manager. Compare two stock assets: {n1} ({ticker1}) and {n2} ({ticker2}) for our fund client.

    Performance Metrics:
    - {n1}: Rating={res1['recommendation']} (Conf={res1['confidence_score']}%). Monthly return={ret1_1m:.2f}%. Yearly return={ret1_1y:.2f}%.
    - {n2}: Rating={res2['recommendation']} (Conf={res2['confidence_score']}%). Monthly return={ret2_1m:.2f}%. Yearly return={ret2_1y:.2f}%.

    Strategic Decisions:
    - Short-Term Preference Winner: {st_winner}
    - Long-Term Preference Winner: {lt_winner}
    - Overall Winner Selection: {overall_winner}

    Write a memo with these exact markdown headers:
    1. **Comparative Strategy Assessment**: Explain why the winner was chosen for short-term and long-term horizons.
    2. **Asset Risk & Returns Profile**: Explain the trade-offs of investing in {n1} versus {n2} (e.g. beta, momentum, valuation boundaries).
    3. **Allocation Recommendations**: Give clear, actionable advice on how an investor should construct a position between these two assets.
    """
    try:
        response = model.generate_content(prompt)
        display(Markdown(response.text))
    except Exception as e:
        print(f"❌ Failed to generate comparative AI report: {e}")

def analyze_sectors():
    """
    Fetches performance metrics across sectors and ranks them, pulling AI macro reviews.
    """
    print("🌐 Fetching live market data for sectors representative stocks...")
    sector_map = {
        "Technology": {
            "TCS.NS": "TCS (India)",
            "INFY.NS": "Infosys (India)",
            "AAPL": "Apple (US)",
            "MSFT": "Microsoft (US)"
        },
        "Financials": {
            "HDFCBANK.NS": "HDFC Bank (India)",
            "ICICIBANK.NS": "ICICI Bank (India)",
            "JPM": "JPMorgan (US)",
            "BAC": "Bank of America (US)"
        },
        "Automobiles": {
            "TATAMOTORS.NS": "Tata Motors (India)",
            "M&M.NS": "Mahindra & Mahindra (India)",
            "TSLA": "Tesla (US)",
            "F": "Ford (US)"
        },
        "Healthcare": {
            "SUNPHARMA.NS": "Sun Pharma (India)",
            "CIPLA.NS": "Cipla (India)",
            "PFE": "Pfizer (US)",
            "JNJ": "Johnson & Johnson (US)"
        },
        "Energy": {
            "RELIANCE.NS": "Reliance (India)",
            "ONGC.NS": "ONGC (India)",
            "XOM": "ExxonMobil (US)",
            "CVX": "Chevron (US)"
        }
    }

    sector_results = []
    for sector_name, tickers in sector_map.items():
        returns = []
        stock_details = []
        for ticker, label in tickers.items():
            df = fetch_stock_data(ticker, period="3mo")
            if df is not None and len(df) > 21:
                ret_1m = ((df['Close'].iloc[-1] - df['Close'].iloc[-21]) / df['Close'].iloc[-21]) * 100
                returns.append(ret_1m)
                stock_details.append(f"{label}: {ret_1m:+.1f}%")
        if returns:
            sector_results.append({
                "Sector": sector_name,
                "Avg_1M_Return": np.mean(returns),
                "Components": ", ".join(stock_details)
            })

    sector_df = pd.DataFrame(sector_results).sort_values(by="Avg_1M_Return", ascending=False)

    display(HTML("<h4 style='color: #2D3748; margin-top:15px;'>Quantitative 1-Month Average Sector Returns</h4>"))
    styled_html = sector_df.style.format({"Avg_1M_Return": "{:+.2f}%"})\
                           .bar(subset=["Avg_1M_Return"], color=['#FEB2B2', '#9AE6B4'], align='zero')\
                           .hide(axis="index")
    display(HTML(styled_html.to_html()))

    print("✍️ Querying Gemini AI for macro sector review...")
    sector_data_str = ""
    for idx, row in sector_df.iterrows():
        sector_data_str += f"- Sector: {row['Sector']}, Avg Return: {row['Avg_1M_Return']:.2f}%, Components: {row['Components']}\n"

    model = genai.GenerativeModel('gemini-2.5-flash')
    prompt = f"""
    You are a macroeconomic investment strategist. Analyze these recent average monthly sector returns:

    {sector_data_str}

    Create a sector strategy research bulletin detailing:
    1. **Sector Rotation Dynamics**: Review which sectors lead/lag and explain the underlying macroeconomic triggers (e.g. interest rates, demand cycle).
    2. **Top Sector Stock Picks**: Highlight 2 specific high-performing stocks from the top performing sectors and write a short thesis for each.
    3. **Tactical Action Plan**: Provide direct advice on sector exposures for conservative vs aggressive portfolios.
    """
    try:
        response = model.generate_content(prompt)
        display(Markdown(response.text))
    except Exception as e:
        print(f"❌ Failed to generate sector AI insights: {e}")

def process_query(query):
    """
    Main entry point for handling natural language questions.
    Determines intent and executes pipelines.
    """
    print(f"💬 Parsing request: \"{query}\"")
    analysis = resolve_tickers_and_intent(query)
    intent = analysis.get("intent", "general_qa")
    tickers = analysis.get("tickers", [])
    companies = analysis.get("companies", [])

    print(f"⚙️ Intent Classification: {intent.upper()} | Resolved Symbols: {tickers}")

    if intent == "single_analysis" and len(tickers) >= 1:
        analyze_single_stock(tickers[0], companies[0] if len(companies) >= 1 else tickers[0])

    elif intent == "compare" and len(tickers) >= 2:
        compare_two_stocks(tickers[0], tickers[1],
                           companies[0] if len(companies) >= 1 else tickers[0],
                           companies[1] if len(companies) >= 2 else tickers[1])

    elif intent == "compare" and len(tickers) == 1:
        print("⚠️ Found only 1 stock for comparison. Falling back to single stock analysis.")
        analyze_single_stock(tickers[0], companies[0] if len(companies) >= 1 else tickers[0])

    elif intent == "sector_recommendation":
        analyze_sectors()

    else:
        # General investing Q&A
        print("💬 Routing general investment questions to Personal AI Advisor...")
        model = genai.GenerativeModel('gemini-2.5-flash')
        prompt = f"""
        You are a highly qualified and professional personal investment adviser.
        Answer this client query: \"{query}\"

        Provide clear, educational, and helpful advice emphasizing:
        - Strategic principles (risk capacity, asset diversification, dollar-cost averaging).
        - Compliant regulatory disclaimers explaining that this is AI educational commentary and not registered advice.
        """
        try:
            response = model.generate_content(prompt)
            display(Markdown(response.text))
        except Exception as e:
            print(f"❌ Q&A failed: {e}")

# Install packages
!pip install yfinance google-generativeai ipywidgets seaborn jinja2 -q

# Imports
import os
import json
import warnings
import getpass

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import google.generativeai as genai

from datetime import datetime, timedelta
from IPython.display import display, HTML, Markdown, clear_output
import ipywidgets as widgets

warnings.filterwarnings("ignore")

# Styling
sns.set_theme(style="darkgrid")

print("✅ All libraries loaded successfully")

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# Query Input
query_box = widgets.Text(
    value='',
    placeholder='Should I invest in Tata Motors? Compare Reliance and Infosys',
    description='Ask:',
    layout=widgets.Layout(width='70%')
)

# Buttons
run_btn = widgets.Button(
    description='Ask Assistant',
    button_style='success',
    icon='search'
)

clear_btn = widgets.Button(
    description='Clear',
    button_style='warning',
    icon='trash'
)

# Output Area
output_window = widgets.Output()

# Ask Button Action
def trigger_analysis(b):
    with output_window:
        clear_output()

        query = query_box.value.strip()

        if not query:
            print("Please enter a question.")
            return

        try:
            process_query(query)
        except Exception as e:
            print("Error:", e)

# Clear Button Action
def trigger_clear(b):
    query_box.value = ""
    with output_window:
        clear_output()

run_btn.on_click(trigger_analysis)
clear_btn.on_click(trigger_clear)

# Header
display(
    HTML("""
    <div style='padding:15px;
                background:#f5f5f5;
                border-radius:10px;
                border:1px solid #ddd'>
        <h2>🤖 AI Powered Investment Assistant</h2>
        <p>Ask stock analysis, comparison, sector recommendations, and investment questions.</p>
    </div>
    """)
)

# Display Dashboard
display(widgets.HBox([query_box]))
display(widgets.HBox([run_btn, clear_btn]))
display(output_window)